export enum Message {
	SOMETHING_WENT_WRONG = 'Something went wrong',
	NO_DATA_FOUND = 'No data is found',
	CREATE_FAILED = 'Create is failed',
	UPDATE_FAILED = 'Update is failed',
	REMOVE_FAILED = 'Remove is failed',
	UPLOAD_FAILED = 'Upload is failed',
	BAD_REQUEST = 'Bad request',
	NO_MEMBER_NICK = 'No member with that member nick!',
	USED_MEMBER_NICK_OR_PHONE = 'Member nick or phone is already used!',
	BLOCKED_USER = 'You have been blocked, contact Reneva support!',
	WRONG_PASSWORD = 'Wrong password, please try again!',
	NOT_AUTHENTICATED = 'You are not authenticated, Please login first!',
	TOKEN_NOT_EXIST = 'Bearer Token is not provided!',
	ONLY_SPECIFIC_ROLES_ALLOWED = 'Allowed only for members with specific roles!',
	NOT_ALLOWED_REQUEST = 'Not Allowed Request!',
	PROVIDE_ALLOWED_FORMAT = 'Please provide jpg, jpeg, or png images!',
	SELF_SUBSCRIPTION_DENIED = 'Self subscription is denied!',
	USED_BRAND_NAME = 'Brand name is already used!',
	USED_CATEGORY_SLUG = 'Category slug is already used!',
	NOT_BRAND_OWNER = 'You can manage only your own brand!',
	OPTION_REQUIRED = 'Product needs at least one option!',
	OUT_OF_STOCK = 'Not enough stock for this option!',
	EMPTY_CART = 'No selected items in the cart!',
	WRONG_ORDER_STATUS = 'Order is not in the right status for this action!',
	COUPON_NOT_AVAILABLE = 'Coupon is not available!',
	COUPON_MIN_ORDER = 'Order total is lower than the coupon minimum!',
	USED_COUPON = 'You already have this coupon!',
	NOT_ENOUGH_POINTS = 'Not enough points!',
	ALREADY_REVIEWED = 'This item is already reviewed!',
	REVIEW_NOT_ALLOWED = 'You can review only delivered items you bought!',
	NOT_CHAT_MEMBER = 'You are not a member of this chat room!',
	SELF_CHAT_DENIED = 'You cannot open a chat with yourself!',
	NO_SUPPORT_AGENT = 'No support agent is available right now!',
	AI_NOT_CONFIGURED = 'AI is not configured, set ANTHROPIC_API_KEY!',
	AI_FAILED = 'AI could not answer, please try again!',
	AI_REFUSED = 'AI could not help with this request.',
}

// GraphQL takes the enum names, not the numbers the server uses inside
export enum Direction {
	ASC = 'ASC',
	DESC = 'DESC',
}
